openapi: 3.0.3
info:
  title: Ad-hoc required PoC
  description: |-
    PoC that shows possibility to add `required` constraint to models' properties in echo request definition.
  version: "1.0"
servers:
  - url: "http://localhost:8089"
paths:
  /api/v1/users:
    $ref: "./paths/api/v1/users.yaml"
  /api/v1/users/{userId}:
    $ref: "./paths/api/v1/user.yaml"
components:
  schemas:
    User:
      $ref: "./schemas/user.yaml"
    UserInfo:
      $ref: "./schemas/userInfo.yaml"
